stripe.secret.key=${STRIPE_SECRET_KEY:}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:}
allowed.origins=${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5175,http://localhost:5174}
server.port=8080